#!/bin/bash
if [ ! -e ~/.gitignore ]; then
	echo ".ycm_extra_conf.py" >> ~/.gitignore
	git config --global core.excludesfile '~/.gitignore'
fi

USER_CONFIGURED=$(git config --global user.name | wc -l)
if (( USER_CONFIGURED < 1 )); then
	read -p "Enter global user.name: " GIT_GLOBAL_USERNAME
	git config --global user.name $GIT_GLOBAL_USERNAME
	read -p "Enter global user.email: " GIT_GLOBAL_EMAIL
	git config --global user.email GIT_GLOBAL_EMAIL
	git config --global credential.helper cache
fi

git config --global push.default simple

