#!/bin/bash
if [ ! -e ~/.gitignore ]; then
	echo ".ycm_extra_conf.py" >> ~/.gitignore
	git config --global core.excludesfile '~/.gitignore'
fi

git config --global user.name makerj
git config --global user.email "ohenwkgdj@gmail.com"
git config --global push.default simple

