#!/bin/bash
git pull -q
cat .makerj

BASE=`pwd`
ESSENTIAL='essential'

if grep -q "16.04" /etc/issue ; then
	cd $ESSENTIAL
	./ppa-setup
	./terminal-setup
	./desktop-setup
	./zsh-setup
	./git-setup
	./vim-setup
	cd $BASE
elif grep -q "18.04" /etc/issue ; then
	cd $ESSENTIAL
	./terminal-setup
	./zsh-setup
	./git-setup
	./vim-setup
	cd $BASE
else
	echo "Unsupported platform"
	cat /etc/issue
	exit 1;
fi

