#!/bin/bash
BASE=`pwd`

# Install Plugin Manager ------------------------------------------------------
if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
	echo "Vundle is not found. cloning..."
	git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

# Install Plugins -------------------------------------------------------------
cp vimrc ~/.vimrc
vim +PluginInstall +qall

# Install Plugins :: CommandT
if [ ! -e ~/.vim/bundle/command-t/ruby/command-t/ext.so ]; then
	sudo apt-get install ack-grep vim-gnome vim-nox vim-rails ruby-dev -y
	cd ~/.vim/bundle/command-t/ruby/command-t
	ruby extconf.rb
	make
	cd $BASE
fi

# Install Plugins :: YouCompleteMe
if [ ! -e ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so ]; then
	sudo apt-get install build-essential cmake clang python-dev python3-dev ack-grep -y
	cd ~/.vim/bundle/YouCompleteMe
	./install.py --clang-completer
fi
## Update ycm_extra_conf everytime
cd ~/.vim
curl -O -L https://raw.githubusercontent.com/makerj/dev/master/ycm_extra_conf.py
cd $BASE

