#!/bin/bash
BASE=`pwd`
if [ ! -e /usr/bin/cmake ]; then
	sudo apt-get install cmake -y
fi
# Install Plugin Manager ------------------------------------------------------
if [ ! -e ~/.vim/autoload/plug.vim ]; then
	echo "Plugin Manager is not found. cloning..."
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install Plugins -------------------------------------------------------------
cp vimrc ~/.vimrc
vim +PlugInstall +qall

# Install Plugins :: YouCompleteMe :: ycm_extra_conf
curl -fLo ~/.vim/ycm_extra_conf.py https://raw.githubusercontent.com/makerj/dev/master/ycm_extra_conf.py
# Install Plugins :: Ack
if [ ! -e /usr/bin/ack-grep ]; then
	sudo apt-get install ack-grep -y
fi

