#!/bin/bash
BASE=`pwd`

# Install Plugin Manager ------------------------------------------------------
if [ ! -e ~/.vim/autoload/plug.vim ]; then
	echo "Plugin Manager is not found. cloning..."
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install Plugins -------------------------------------------------------------
cp vimrc ~/.vimrc
vim +PlugInstall +qall

# Install Plugins :: YouCompleteMe
if [ ! -e ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so ]; then
	sudo apt-get install build-essential cmake clang python-dev python3-dev ack-grep -y
	cd ~/.vim/bundle/YouCompleteMe
	./install.py --clang-completer
fi
## Update ycm_extra_conf everytime
cd ~/.vim
curl -O -L https://raw.githubusercontent.com/makerj/dev/master/ycm_extra_conf.py
cd $BASE

