#!/bin/bash

# Essential Utilties ------------------------------------------------------------------------------
if [ ! -e /usr/bin/indicator-multiload ]; then
	sudo apt-get install \
		curl build-essential git indicator-multiload \
		unity-tweak-tool compizconfig-settings-manager compiz-plugins -y
fi

if [ ! -e /usr/bin/fzf ]; then
	curl -O -L https://github.com/junegunn/fzf-bin/releases/download/0.16.7/fzf-0.16.7-linux_amd64.tgz
	tar xf fzf-0.16.7-linux_amd64.tgz
	sudo mv fzf /usr/bin/fzf
	rm fzf-0.16.7-linux_amd64.tgz
fi

# zsh ---------------------------------------------------------------------------------------------
if [ ! -e /usr/bin/zsh ]; then
	sudo apt-get install zsh -y
	chsh -s /usr/bin/zsh
fi
if [ ! -e ~/.oh-my-zsh ]; then
	mkdir -p ${HOME}/.oh-my-zsh
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi
if [ ! -e ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
	git clone git://github.com/zsh-users/zsh-autosuggestions \
		${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi
if [ ! -e ~/.oh-my-zsh/z.sh ]; then
	curl -O -L https://raw.githubusercontent.com/rupa/z/master/z.sh
	mv z.sh ~/.oh-my-zsh/z.sh
fi

cp zshrc ~/.zshrc

