#!/bin/bash
if [ ! -e /usr/bin/indicator-multiload ]; then
	# Essentials
	sudo apt-get install curl build-essential git indicator-multiload unity-tweak-tool compizconfig-settings-manager compiz-plugins -y
fi

if [ ! -e /usr/bin/zsh ]; then
	# install zsh
	sudo apt-get install zsh -y
	chsh -s /usr/bin/zsh
	# install oh-my-zsh
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
	# install zsh-autosuggestions
	git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
	# install z
	curl -O -L https://raw.githubusercontent.com/rupa/z/master/z.sh
	mv z.sh ~/.oh-my-zsh/z.sh
fi


if [ ! -e /usr/bin/fzf ]; then
	curl -O -L https://github.com/junegunn/fzf-bin/releases/download/0.16.7/fzf-0.16.7-linux_amd64.tgz
	tar xf fzf-0.16.7-linux_amd64.tgz
	sudo mv fzf /usr/bin/fzf
	rm fzf-0.16.7-linux_amd64.tgz
fi

cp zshrc ~/.zshrc
