#!/bin/bash
if hash X; then
	PACKAGE_LIST=$(dpkg --get-selections)

	INDICATOR_EXISTS=$(echo $PACKAGE_LIST | grep indicator-multiload | wc -l)
	if (( $INDICATOR_EXISTS < 1 )); then
		sudo apt install indicator-multiload -y
	fi

	if (( $UBUNTU_18_04 )); then
		sudo apt-get -qq install ubuntu-unity-desktop -y
		sudo apt-get -qq install network-manager. -y
	fi

	UNITY_TWEAK_TOOL_EXISTS=$(echo $PACKAGE_LIST | grep unity-tweak-tool | wc -l)
	if (( $UNITY_TWEAK_TOOL_EXISTS < 1 )); then
		sudo apt install unity-tweak-tool -y
	fi

	if (( $UBUNTU_18_04 < 1 )); then
		PAPER_THEME_EXISTS=$(echo $PACKAGE_LIST | grep paper-gtk-theme | wc -l)
		if (( $PAPER_THEME_EXISTS < 1 )); then
			sudo apt update
			sudo apt install paper-icon-theme paper-gtk-theme -y
			gsettings set org.gnome.desktop.interface gtk-theme 'Paper'
			gsettings set org.gnome.desktop.interface icon-theme 'Paper'
		fi
	fi

	COMPIZ_PLUGINS_EXISTS=$(echo $PACKAGE_LIST | grep compizconfig-settings-manager | wc -l)
	if (( $COMPIZ_PLUGINS_EXISTS < 1 )); then
		sudo apt install compizconfig-settings-manager compiz-plugins -y
	fi

	APPORT_EXISTS=$(echo $PACKAGE_LIST | grep apport-gtk | wc -l)
	if (( $APPORT_EXISTS )); then
		# Removing annoying ubuntu internal error report popups
		sudo apt purge apport -y
	fi

	sudo apt-get -qq install kolourpaint -y
fi

