#!/bin/bash
if hash X; then
	if [ ! -e /usr/bin/indicator-multiload ]; then
		sudo apt-get install indicator-multiload -y
	fi

	PAPER_THEME_EXISTS=$(apt-cache policy | grep snwh | wc -l)
	if (( $PAPER_THEME_EXISTS < 1 )); then
		sudo apt-get install paper-icon-theme paper-gtk-theme unity-tweak-tool -y
	fi

	COMPIZ_PLUGINS_EXISTS=$(dpkg --get-selections | grep compizconfig-settings-manager | wc -l)
	if (( $COMPIZ_PLUGINS_EXISTS < 1 )); then
		sudo apt-get install compizconfig-settings-manager compiz-plugins -y
	fi

	if ! hash hwpviewer; then
		curl -O -L http://cdn.hancom.com/pds/hnc/VIE/hwpviewer_9.20.0.347_amd64.deb
		sudo dpkg -i hwpviewer_9.20.0.347_amd64.deb
		sudo apt-get install -f -y
		rm -f hwpviewer_9.20.0.347_amd64.deb
	fi
fi

