#!/bin/bash
if ! hash git; then
	sudo apt-get install git -y
fi

USER_CONFIGURED=$(git config --global user.name | wc -l)
if (( USER_CONFIGURED < 1 )); then
	read -p "Enter global user.name: " GIT_GLOBAL_USERNAME
	git config --global user.name $GIT_GLOBAL_USERNAME
	read -p "Enter global user.email: " GIT_GLOBAL_EMAIL
	git config --global user.email GIT_GLOBAL_EMAIL
fi

git config --global credential.helper cache
git config --global help.autocorrect 1
git config --global push.default simple

cp gitignore ~/.gitignore
git config --global core.excludesfile '~/.gitignore'
