#!/bin/bash
BASE=`pwd`
sudo echo " "

if [ ! -e /usr/bin/cmake ]; then
	sudo apt-get install cmake -y
fi
# Install Plugin Manager ------------------------------------------------------
if [ ! -e ~/.vim/autoload/plug.vim ]; then
	echo "Plugin Manager is not found. cloning..."
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install Plugins -------------------------------------------------------------
export PLUGIN_BASE="$HOME/.vim/plugged"
cp vimrc ~/.vimrc
vim +PlugInstall +qall

# Install Plugins :: YouCompleteMe
export YCM_BASE="$PLUGIN_BASE/YouCompleteMe"
./vim-ycm-language-support
cp ycm_extra_conf.py ~/.vim/

