#!/bin/bash
BASE=`pwd`
sudo echo " "

# Install latest vim ----------------------------------------------------------
VIM_PPA_EXISTS=$(apt-cache policy | grep "pi-rho" | wc -l)
if (( $VIM_PPA_EXISTS < 1 )); then
	sudo apt-get install cmake python-dev -y
	sudo apt-get install vim vim-nox vim-rails -y
	if hash X; then
		sudo apt-get install vim-gnome -y # For clipboard sharing
	fi
fi

# Install utilities ------------------------------------------------------------
if ! hash ctags; then
	sudo apt-get install automake -y
	git clone https://github.com/universal-ctags/ctags.git
	cd ctags
	./autogen.sh && ./configure && sudo make install
	cd $BASE && rm -rf ctags
fi
if ! hash cscope; then
	sudo apt-get install cscope -y
fi

# Install Plugin Manager ------------------------------------------------------
if [ ! -e ~/.vim/autoload/plug.vim ]; then
	echo "Plugin Manager is not found. cloning..."
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install Plugins -------------------------------------------------------------
export PLUGIN_BASE="$HOME/.vim/plugged"
cp vimrc ~/.vimrc
vim +PlugUpdate +qall

# Install Plugins :: YouCompleteMe
export YCM_BASE="$PLUGIN_BASE/YouCompleteMe"
./vim-ycm-language-support
cp ycm_extra_conf.py ~/.vim/

# Install Plugins :: fzf.vim :: Ag
if ! hash ag; then
	sudo apt-get install silversearcher-ag -y
fi

