#!/bin/bash
if [[ ! -e $YCM_BASE ]]; then
	echo "YouCompleteMe Base($YCM_BASE) is not found"
	exit
fi

YCM_LANG_CONFIG="$HOME/.vim/ycm-languages"
INSTALL_REQUIRED=0

# C Family Support ------------------------------------------------------------
if [[ ! -e $YCM_LANG_CONFIG ]]; then
	touch $YCM_LANG_CONFIG
	echo "--clang-completer" >> $YCM_LANG_CONFIG
	INSTALL_REQUIRED=1
fi

# Java Support ----------------------------------------------------------------
if hash javac; then
	LS_EXISTS=$(grep 'java' $YCM_LANG_CONFIG | wc -l)
	if (( ! $LS_EXISTS )); then
		echo "--java-completer" >> $YCM_LANG_CONFIG
		INSTALL_REQUIRED=1
	fi
fi

# Javascript Support ----------------------------------------------------------
if hash tern; then
	TERN_EXISTS=$(grep 'js' $YCM_LANG_CONFIG | wc -l)
	if (( ! $TERN_EXISTS )); then
		echo "--js-completer" >> $YCM_LANG_CONFIG
		INSTALL_REQUIRED=1
	fi
fi

# Go Support -----------------------------------------------------------------
if [[ -e /usr/local/go ]]; then
	GOCODE_EXISTS=$(grep 'gocode' $YCM_LANG_CONFIG | wc -l)
	if (( ! $GOCODE_EXISTS )); then
		echo "--gocode-completer" >> $YCM_LANG_CONFIG
		INSTALL_REQUIRED=1
	fi
fi

# # Rust Support ---------------------------------------------------------------
# if [[ -e $HOME/.cargo/bin/rustc ]]; then
# 	RACER_EXISTS=$(grep 'racer' $YCM_LANG_CONFIG | wc -l)
# 	if (( ! $RACER_EXISTS )); then
# 		echo "--racer-completer" >> $YCM_LANG_CONFIG
# 		INSTALL_REQUIRED=1
# 	fi
# fi

if (( $INSTALL_REQUIRED )); then
	cd $YCM_BASE
	./install.py --all --clangd-completer
fi
