#!/bin/bash
BASE=`pwd`

# Install latest vim ----------------------------------------------------------
VIM8=$(vim --version | head -n 1 | grep "8.[0-9]" | wc -l)
if (( ! $VIM8 )); then
	# PPA is already preapred. @see ppa-setup
	sudo apt install cmake python-dev -y
	sudo apt install vim vim-nox vim-rails -y
	if hash X; then
		sudo apt install vim-gnome -y # For clipboard sharing
	fi
fi

# Install utilities ------------------------------------------------------------
if ! hash ctags; then
	sudo apt install automake pkg-config libjansson-dev -y
	git clone https://github.com/universal-ctags/ctags.git
	cd ctags
	./autogen.sh && ./configure && sudo make install
	cd $BASE && rm -rf ctags
fi

# Install Plugin Manager ------------------------------------------------------
if [ ! -e ~/.vim/autoload/plug.vim ]; then
	echo "Plugin Manager is not found. cloning..."
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install Plugins -------------------------------------------------------------
export PLUGIN_BASE="$HOME/.vim/plugged"
cp vimrc ~/.vimrc
vim +PlugUpdate +qall

# Install Plugins :: YouCompleteMe
export YCM_BASE="$PLUGIN_BASE/YouCompleteMe"
./vim-ycm-language-support
cp ycm_extra_conf.py ~/.vim/
cp tern-project ~/.tern-project

# Install Plugins :: fzf.vim :: Ag
if ! hash ag; then
	sudo apt install silversearcher-ag -y
fi

# Install External Documents
# C and POSIX
sudo apt-get install -qq glibc-doc manpages-posix-dev -y
# C++
sudo apt-get install -qq libc++-dev libstdc++-`gcc -dumpversion`-doc cppman -y

