"Plugins ----------------------------------------------------------------------
call plug#begin()
Plug 'scrooloose/nerdtree',             {'on': ['NERDTreeToggle', 'NERDTreeClose']}
Plug 'Xuyuanp/nerdtree-git-plugin',     {'on': 'NERDTreeToggle'}
Plug 'junegunn/fzf',					{'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'Valloric/YouCompleteMe'
Plug 'rdnetto/YCM-Generator',			{'on': 'YcmGenerateConfig'}
Plug 'morhetz/gruvbox'
Plug 'benmills/vimux'
Plug 'ntpeters/vim-better-whitespace'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'
Plug 'matze/vim-move'
Plug 'vim-scripts/DoxygenToolkit.vim',	{'on': 'Dox'}
"Plug 'tpope/vim-sleuth' "Indent Detctor
Plug 'vim-scripts/Conque-GDB',          {'on': 'ConqueGdb'}
Plug 'leafgarland/typescript-vim'
Plug 'rust-lang/rust.vim'
Plug 'qpkorr/vim-bufkill'
Plug 'makerj/vim-transit'
Plug 'makerj/vim-pdf'
Plug 'makerj/vim-numbering'
Plug 'makerj/vim-parsenumber' " Show number literal in various perspective
Plug 'makerj/vim-cpp-enhanced-highlight'
Plug 'makerj/felis-cat-igirisu-toast-express' " ESC to english mode for fcitx IM
Plug 'vim-scripts/YankRing.vim' " Circular clipboard
Plug 'makerj/tagbar' " Source outline viewer (ctags required)
Plug 'hari-rangarajan/CCTree' " C Call Tree generator/viewer (cscope required)
call plug#end()

"Basic Setups -----------------------------------------------------------------
set number
set softtabstop=4
set tabstop=4
set shiftwidth=4 "set expandtab " use whitespace for tab character
set cindent
set incsearch
set hlsearch
set ignorecase
set smartcase
set laststatus=2
set title
set smartindent
set autoindent
set autoread
set autowriteall
set updatetime=60
au CursorHold * checktime
set noswapfile
set cursorline
set clipboard=unnamedplus
syntax on
let g:load_doxygen_syntax=1
if filereadable(expand("$HOME/.vim/plugged/gruvbox/colors/gruvbox.vim"))
    colorscheme gruvbox
endif
set bg=dark
"Remember last buffer position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

"Plugin Setups -----------------------------------------------------------------
let g:tagbar_expand = 1
let g:tagbar_autoshowtag = 1

let g:transit_src = 'ko'
let g:transit_dst = 'en'

let g:ycm_global_ycm_extra_conf = expand("$HOME/.vim/ycm_extra_conf.py")
let g:ycm_confirm_extra_conf = 0
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_python_binary_path = 'python3'
let g:ycm_rust_src_path = expand("$HOME/.cargo/rust/src")


let g:ConqueGdb_Leader = '\'
"ConqueGdb_Leader r => run
"ConqueGdb_Leader b => break-create
"ConqueGdb_Leader d => break-delete
"ConqueGdb_Leader s => step
"ConqueGdb_Leader n => next
"ConqueGdb_Leader p => print value
"
let g:airline#extensions#tabline#enabled = 1

let g:UltiSnipsExpandTrigger="<C-right>"

let g:move_key_modifier = 'C'

let g:DoxygenToolkit_briefTag_pre=""

let g:yankring_history_dir=expand("$HOME/.vim")

"Shortcuts --------------------------------------------------------------------
let mapleader=","
"Shortcuts :: Plugin
noremap <F2> :NERDTreeToggle<CR> :vertical resize 50<CR>
noremap <F3> :TagbarToggle<CR>
func! s:CCTreeLoad()
    " Smart cscope database loader
    if filereadable('cscope.xref')
        :CCTreeLoadXRefDB cscope.xref
    elseif filereadable('cscope.out')
        :CCTreeLoadDB cscope.out
        :CCTreeSaveXRefDB cscope.xref
    else
        let l:errmsg = 'CCTree: cscope database is not found. aborting'
        echohl WarningMsg | echo l:errmsg  | echohl None
    endif
endfunc
nnoremap <silent> <F4> :call <SID>CCTreeLoad()<CR>

nnoremap <C-e> :Buffers<CR>
nnoremap <S-e> :Files<CR>

nnoremap <leader>q :YcmCompleter GetDoc<CR>
nnoremap <leader>f :YcmCompleter FixIt<CR>
nnoremap <C-i> :YcmCompleter GoToDeclaration<CR>
nnoremap <C-o> <C-o>zz

nnoremap <leader>d :Dox<CR>
nnoremap <leader>n :ParseNumber<CR>
nnoremap <leader>j :CCTreeTraceForward<CR>
nnoremap <leader>J :CCTreeTraceReverse<CR>

"Shortcuts :: Editor
nnoremap ; :
nnoremap _ zc
nnoremap + zo
nnoremap <leader>g :execute ":Ag ".expand("<cword>")<CR>
nnoremap <leader>e :bn<CR>
nnoremap <leader>w :bp<CR>
nnoremap <leader>z :BD<CR>
nnoremap <F12> <ESC><ESC>:wqa!<CR>
nnoremap <F8> :setlocal ts=8 sts=8 tw=8<CR>
nnoremap <BS> hx
inoremap <C-w> <C-o>de
inoremap <C-b> <C-o>db
nnoremap <leader>t :TransItSwapLang<CR>
vnoremap t :TransItBlock<CR>
vnoremap T :TransItBlockPut<CR>
nnoremap <Space> <C-w>w
nnoremap <silent> <leader><Space> :ToggleNumbering<CR>
nnoremap <C-l> :Lines<CR>

"Shortcuts :: External Utilties
nnoremap <F9> :!$SHELL<CR>
nnoremap <F10> :wa<CR><ESC>:!make<CR>
nnoremap <C-F10> :wa<CR><ESC>:!make test<CR>

