#!/bin/bash

# zsh ---------------------------------------------------------------------------------------------
if ! hash zsh; then
	sudo apt-get install zsh -y
	chsh -s /usr/bin/zsh
fi
if [ ! -e ~/.oh-my-zsh ]; then
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi
if [ ! -e ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
	git clone git://github.com/zsh-users/zsh-autosuggestions \
		${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi
if [ ! -e ~/.oh-my-zsh/z.sh ]; then
	curl -O -L https://raw.githubusercontent.com/rupa/z/master/z.sh
	mv z.sh ~/.oh-my-zsh/z.sh
fi

cp zshrc ~/.zshrc

if [ ! -e ~/.zshrc-credential ]; then
	read -p "Enter Google Cloud API Key: " GOOGLE_CLOUD_API_KEY
	if [ ! -z $GOOGLE_CLOUD_API_KEY ]; then
		echo "export GOOGLE_CLOUD_API_KEY=$GOOGLE_CLOUD_API_KEY" >> ~/.zshrc-credential
	fi
fi
