#!/bin/bash

# zsh ---------------------------------------------------------------------------------------------
if ! hash zsh; then
	sudo apt install zsh -y
	chsh -s /usr/bin/zsh
fi
if [ ! -e ~/antigen.zsh ]; then
	curl -L git.io/antigen > ~/antigen.zsh
fi

if [ ! -e ~/.zshrc-credential ]; then
	read -p "Enter Google Cloud API Key: " GOOGLE_CLOUD_API_KEY
	if [ ! -z $GOOGLE_CLOUD_API_KEY ]; then
		echo "export GOOGLE_CLOUD_API_KEY=$GOOGLE_CLOUD_API_KEY" >> ~/.zshrc-credential
	fi
fi

sudo apt-get install -qq linux-tools-common
sudo apt-get install -qq linux-tools-`uname -r`
if [[ ! -e ~/.FlameGraph ]]; then
	git clone https://github.com/brendangregg/FlameGraph.git ~/.FlameGraph
fi

cp zshrc ~/.zshrc
